import { EmbedBuilder, SlashCommandBuilder, MessageFlags } from 'discord.js';
import { EMBED_COLOR } from '../config/settings.js';
import { CountryManager } from '../world/CountryManager.js';
import { BattleResolver } from '../warfare/BattleResolver.js';
import { WarNotificationService } from '../notifications/WarNotificationService.js';
import { WorldWarManager } from '../global_war/WorldWarManager.js';
import { proMissionManager } from '../pro/ProMissionManager.js';
const countries=new CountryManager(), battles=new BattleResolver(), notify=new WarNotificationService(), worldWars=new WorldWarManager({countries});
export default{data:new SlashCommandBuilder().setName('atacar').setDescription('Resolve uma batalha territorial abstrata.').addStringOption(o=>o.setName('conflito').setDescription('ID do conflito').setRequired(true)).addStringOption(o=>o.setName('origem').setDescription('Território de origem').setRequired(true)).addStringOption(o=>o.setName('alvo').setDescription('Território alvo adjacente').setRequired(true)).addStringOption(o=>o.setName('unidades').setDescription('IDs das unidades, separados por vírgula').setRequired(true)),async execute(i){try{const c=countries.memberCountry(i.user.id);if(!c)throw new Error('Você não pertence a um país.');if(c.leader_id!==String(i.user.id))throw new Error('Apenas o líder pode ordenar ataques.');const unitIds=i.options.getString('unidades',true).split(',').map(x=>x.trim()).filter(Boolean);const b=battles.resolve({conflictId:i.options.getString('conflito',true),attackerCountryId:c.id,originTerritoryId:i.options.getString('origem',true),targetTerritoryId:i.options.getString('alvo',true),unitIds,actorId:i.user.id});const e=new EmbedBuilder().setColor(EMBED_COLOR).setTitle('⚔️ Batalha resolvida').addFields({name:'Resultado',value:b.winner_country_id===c.id?'✅ Vitória':'🛡️ Defesa venceu',inline:true},{name:'Pontuação',value:`Ataque **${b.attacker_score}** × Defesa **${b.defender_score}**`,inline:true},{name:'Perdas abstratas',value:`Ataque: **-${b.attacker_readiness_loss}** prontidão\nDefesa: **-${b.defender_readiness_loss}** prontidão`},{name:'Controle territorial',value:b.territory_conquered?'🏳️ Controle transferido ao atacante.':'Sem alteração.'});await notify.battle(i,b);if(worldWars.activeForCountry(c.id))proMissionManager.record(i.user.id,'global_war_battle_participation',1);await i.reply({embeds:[e],flags: MessageFlags.Ephemeral})}catch(e){await i.reply({content:`❌ ${e.message}`,flags: MessageFlags.Ephemeral})}}};
