import { ChannelType, PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import { GameChannelManager } from '../notifications/GameChannelManager.js';
import { NotificationManager } from '../notifications/NotificationManager.js';
const channels=new GameChannelManager(), notifications=new NotificationManager({channels});
const typeOption=o=>o.setName('tipo').setDescription('Tipo de canal').setRequired(true).addChoices({name:'📈 Mercado',value:'market'},{name:'🔄 Trocas',value:'trades'},{name:'🚨 Guerra',value:'war'},{name:'🌐 Mundial',value:'world'});
export default {data:new SlashCommandBuilder().setName('configurarcanais').setDescription('Configura os canais públicos do jogo.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
.addSubcommand(s=>s.setName('definir').setDescription('Define um canal.').addStringOption(typeOption).addChannelOption(o=>o.setName('canal').setDescription('Canal de texto').addChannelTypes(ChannelType.GuildText).setRequired(true)))
.addSubcommand(s=>s.setName('listar').setDescription('Lista os canais configurados.'))
.addSubcommand(s=>s.setName('remover').setDescription('Remove um canal configurado.').addStringOption(typeOption))
.addSubcommand(s=>s.setName('testar').setDescription('Envia uma mensagem de teste.').addStringOption(typeOption)),
async execute(i){try{if(!i.guildId)throw new Error('Use em um servidor.');const sub=i.options.getSubcommand();if(sub==='definir'){const t=i.options.getString('tipo',true),c=i.options.getChannel('canal',true);channels.set(i.guildId,t,c.id);return i.reply({content:`✅ Canal **${t}** definido como ${c}.`,ephemeral:true});}if(sub==='remover'){const t=i.options.getString('tipo',true);channels.remove(i.guildId,t);return i.reply({content:`✅ Canal **${t}** removido.`,ephemeral:true});}if(sub==='listar'){const c=channels.get(i.guildId);const txt=['market','trades','war','world'].map(t=>`**${t}**: ${c[t]?`<#${c[t]}>`:'não configurado'}`).join('\n');return i.reply({content:txt,ephemeral:true});}const t=i.options.getString('tipo',true);const r=await notifications.send(i,i.guildId,t,{title:'Teste de notificações',emoji:'🧪',description:`Canal **${t}** configurado corretamente.`});await i.reply({content:r.sent?'✅ Mensagem de teste enviada.':`❌ Não foi possível enviar: ${r.reason}`,ephemeral:true});}catch(e){await i.reply({content:`❌ ${e.message}`,ephemeral:true});}}};
