import { SlashCommandBuilder } from 'discord.js';
import { PlayerTradeManager } from '../trades/PlayerTradeManager.js';
import { TradeNotificationService } from '../notifications/TradeNotificationService.js';
const trades=new PlayerTradeManager(), notify=new TradeNotificationService();
const idOpt=s=>s.addStringOption(o=>o.setName('id').setDescription('ID da troca').setRequired(true));
export default {data:new SlashCommandBuilder().setName('trocar').setDescription('Trocas diretas e seguras entre jogadores.')
.addSubcommand(s=>s.setName('propor').setDescription('Propõe uma troca.').addUserOption(o=>o.setName('jogador').setDescription('Destinatário').setRequired(true)).addStringOption(o=>o.setName('oferece_item').setDescription('ID do item que você oferece')).addIntegerOption(o=>o.setName('oferece_qtd').setDescription('Quantidade oferecida').setMinValue(1)).addNumberOption(o=>o.setName('oferece_dinheiro').setDescription('Dinheiro oferecido').setMinValue(0.01)).addStringOption(o=>o.setName('pede_item').setDescription('ID do item solicitado')).addIntegerOption(o=>o.setName('pede_qtd').setDescription('Quantidade solicitada').setMinValue(1)).addNumberOption(o=>o.setName('pede_dinheiro').setDescription('Dinheiro solicitado').setMinValue(0.01)))
.addSubcommand(s=>idOpt(s.setName('aceitar').setDescription('Aceita uma proposta recebida.'))).addSubcommand(s=>idOpt(s.setName('recusar').setDescription('Recusa uma proposta recebida.'))).addSubcommand(s=>idOpt(s.setName('cancelar').setDescription('Cancela uma proposta enviada.'))).addSubcommand(s=>s.setName('minhas').setDescription('Lista suas trocas recentes.')),
async execute(i){try{const sub=i.options.getSubcommand();if(sub==='propor'){const target=i.options.getUser('jogador',true);if(target.bot)throw new Error('Bots não podem participar de trocas.');const tr=trades.propose({guildId:i.guildId,proposerId:i.user.id,targetId:target.id,offerItemId:i.options.getString('oferece_item'),offerQuantity:i.options.getInteger('oferece_qtd')??0,offerMoney:i.options.getNumber('oferece_dinheiro')??0,requestItemId:i.options.getString('pede_item'),requestQuantity:i.options.getInteger('pede_qtd')??0,requestMoney:i.options.getNumber('pede_dinheiro')??0});await notify.proposal(i,tr);return i.reply({content:`✅ Proposta criada: \`${tr.id}\`. O que você ofereceu ficou reservado até aceitar, recusar ou cancelar.`,ephemeral:true});}if(sub==='minhas'){const list=trades.listFor(i.user.id).slice(-10).reverse();return i.reply({content:list.length?list.map(t=>`\`${t.id}\` • **${t.status}** • <@${t.proposer_id}> ↔ <@${t.target_id}>`).join('\n'):'Nenhuma troca encontrada.',ephemeral:true});}const id=i.options.getString('id',true);if(sub==='aceitar'){const tr=trades.accept(i.user.id,id);await notify.completed(i,tr);return i.reply({content:'✅ Troca concluída.',ephemeral:true});}if(sub==='recusar'){trades.reject(i.user.id,id);return i.reply({content:'✅ Troca recusada e reserva devolvida.',ephemeral:true});}trades.cancel(i.user.id,id);return i.reply({content:'✅ Troca cancelada e reserva devolvida.',ephemeral:true});}catch(e){await i.reply({content:`❌ ${e.message}`,ephemeral:true});}}};
