import { InventoryManager } from '../inventory/InventoryManager.js';
import { ProfileManager } from '../players/ProfileManager.js';
import { EnergyManager } from '../players/EnergyManager.js';
import { StatisticsManager } from '../players/StatisticsManager.js';
import { RecipeRegistry } from '../production/RecipeRegistry.js';
import { MilitaryFacilityManager } from './MilitaryFacilityManager.js';
import { MilitaryStorageManager } from './MilitaryStorageManager.js';
import { ItemRegistry } from '../core/ItemRegistry.js';

export class MilitaryProductionManager{
 constructor(){this.inventory=new InventoryManager();this.profiles=new ProfileManager();this.energy=new EnergyManager(this.profiles);this.statistics=new StatisticsManager();this.recipes=new RecipeRegistry();this.facilities=new MilitaryFacilityManager();this.storage=new MilitaryStorageManager();this.items=new ItemRegistry();}
 canCraft(userId,recipeId,amount=1){const count=Math.trunc(Number(amount));if(count<=0)return [false,'Quantidade inválida.'];const r=this.recipes.get(recipeId);if(!r||r.category!=='military')return [false,'Receita estratégica não encontrada.'];const p=this.profiles.get(userId);if(!p)return [false,'Perfil não encontrado. Use /game primeiro.'];if(Number(p.level||1)<Number(r.required_level||1))return [false,`Nível ${r.required_level} necessário.`];if(this.facilities.getLevel(userId,r.facility)<Number(r.facility_level||1))return [false,`Necessário ${r.facility} nível ${r.facility_level||1}.`];const energy=Number(r.energy_cost||0)*count;if(!this.energy.has(userId,energy))return [false,'Energia insuficiente.'];for(const [id,q] of Object.entries(r.inputs??{}))if(!this.inventory.hasItem(userId,id,Number(q)*count))return [false,`Falta ${id} (${Number(q)*count}).`];const out=this.items.get(r.output?.item_id);if(!out)return [false,'Produto de saída inválido.'];const type=String(out.storage_type||'military_depot');const [can,msg]=this.storage.canStore(userId,type,r.output.item_id,Number(r.output.quantity||1)*count);if(!can)return [false,msg];return [true,'Produção estratégica disponível.'];}
 craft(userId,recipeId,amount=1){const count=Math.trunc(Number(amount)),[ok,msg]=this.canCraft(userId,recipeId,count);if(!ok)return [false,msg,null];const r=this.recipes.get(recipeId),consumed=[];for(const [id,q] of Object.entries(r.inputs??{})){const qty=Number(q)*count;const [removed]=this.inventory.removeItem(userId,id,qty);if(!removed){for(const x of consumed)this.inventory.addItem(userId,x.id,x.qty,50);return [false,'Falha ao consumir materiais.',null]}consumed.push({id,qty})}const energy=Number(r.energy_cost||0)*count;if(energy&&!this.energy.consume(userId,energy)){for(const x of consumed)this.inventory.addItem(userId,x.id,x.qty,50);return [false,'Falha ao consumir energia.',null]}const itemId=r.output.item_id,qty=Number(r.output.quantity||1)*count,quality=Math.max(1,Math.min(100,Math.trunc(Number(r.base_quality||50)+Math.max(0,this.facilities.getLevel(userId,r.facility)-1)*2)));const type=String(this.items.get(itemId)?.storage_type||'military_depot');const [added,addMsg]=this.storage.addItem(userId,type,itemId,qty,quality);if(!added){if(energy)this.energy.add(userId,energy);for(const x of consumed)this.inventory.addItem(userId,x.id,x.qty,50);return [false,`${addMsg} Operação revertida.`,null]}this.statistics.increment(userId,'military_items_produced',qty);return [true,'Produção estratégica concluída.',{recipe_id:recipeId,item_id:itemId,quantity:qty,quality,storage:type,energy_used:energy}];}
}
