import path from 'node:path';import crypto from 'node:crypto';
import { JsonManager } from '../core/JsonManager.js';import { DIPLOMACY_DATA_DIR } from '../config/settings.js';
import { CountryManager } from '../world/CountryManager.js';import { RelationManager } from './RelationManager.js';
const FILE=path.join(DIPLOMACY_DATA_DIR,'alliances.json');const clone=v=>structuredClone(v);
export class AllianceManager{
 constructor({countries=new CountryManager(),relations=new RelationManager()}={}){this.countries=countries;this.relations=relations;JsonManager.ensureFile(FILE,[])}
 load(){const d=JsonManager.load(FILE,[]);return Array.isArray(d)?d:[]} save(d){JsonManager.save(FILE,d)}
 get(id){return clone(this.load().find(x=>x.id===String(id))??null)} list(){return this.load().map(clone)}
 countryAlliance(countryId){return clone(this.load().find(x=>x.status==='active'&&(x.member_country_ids??[]).includes(String(countryId)))??null)}
 create({founderCountryId,actorId,name,tag}){const c=this.countries.get(founderCountryId);if(!c)throw new Error('País não encontrado.');if(c.leader_id!==String(actorId))throw new Error('Apenas o líder pode criar uma aliança.');if(this.countryAlliance(c.id))throw new Error('Seu país já pertence a uma aliança.');const clean=String(name??'').trim().slice(0,60),t=String(tag??'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);if(clean.length<3||t.length<2)throw new Error('Nome ou sigla da aliança inválidos.');if(this.load().some(x=>x.tag===t&&x.status==='active'))throw new Error('Sigla já utilizada.');const now=new Date().toISOString(),a={id:`alliance_${crypto.randomUUID()}`,name:clean,tag:t,founder_country_id:c.id,leader_country_id:c.id,member_country_ids:[c.id],pending_country_ids:[],status:'active',created_at:now,updated_at:now};const all=this.load();all.push(a);this.save(all);return clone(a)}
 invite(allianceId,targetCountryId,actorId){const all=this.load(),i=all.findIndex(x=>x.id===String(allianceId));if(i<0)throw new Error('Aliança não encontrada.');const a=all[i],leader=this.countries.get(a.leader_country_id);if(leader?.leader_id!==String(actorId))throw new Error('Apenas o líder da aliança pode convidar.');if(!this.countries.get(targetCountryId))throw new Error('País alvo não encontrado.');if(this.countryAlliance(targetCountryId))throw new Error('País alvo já pertence a uma aliança.');const id=String(targetCountryId);if(!a.pending_country_ids.includes(id))a.pending_country_ids.push(id);a.updated_at=new Date().toISOString();this.save(all);return clone(a)}
 accept(allianceId,countryId,actorId){const all=this.load(),i=all.findIndex(x=>x.id===String(allianceId));if(i<0)throw new Error('Aliança não encontrada.');const a=all[i],c=this.countries.get(countryId);if(!c||c.leader_id!==String(actorId))throw new Error('Apenas o líder do país pode aceitar.');if(!a.pending_country_ids.includes(c.id))throw new Error('Seu país não possui convite pendente.');if(this.countryAlliance(c.id))throw new Error('Seu país já pertence a uma aliança.');a.pending_country_ids=a.pending_country_ids.filter(x=>x!==c.id);for(const m of a.member_country_ids)this.relations.set(m,c.id,80,'entrada em aliança');a.member_country_ids.push(c.id);a.updated_at=new Date().toISOString();this.save(all);return clone(a)}
 leave(countryId,actorId){const all=this.load(),i=all.findIndex(x=>x.status==='active'&&(x.member_country_ids??[]).includes(String(countryId)));if(i<0)throw new Error('País não pertence a uma aliança.');const c=this.countries.get(countryId);if(c?.leader_id!==String(actorId))throw new Error('Apenas o líder do país pode sair.');const a=all[i];if(a.leader_country_id===c.id&&a.member_country_ids.length>1)throw new Error('Transfira a liderança da aliança antes de sair.');a.member_country_ids=a.member_country_ids.filter(x=>x!==c.id);if(!a.member_country_ids.length)a.status='dissolved';a.updated_at=new Date().toISOString();this.save(all);return clone(a)}
 areAllied(a,b){const x=this.countryAlliance(a);return !!x&&(x.member_country_ids??[]).includes(String(b))}
}
