import path from 'node:path';import crypto from 'node:crypto';import { JsonManager } from '../core/JsonManager.js';import { DIPLOMACY_DATA_DIR } from '../config/settings.js';import { CountryManager } from '../world/CountryManager.js';import { RelationManager } from './RelationManager.js';
const FILE=path.join(DIPLOMACY_DATA_DIR,'restrictions.json');const clone=v=>structuredClone(v);
export class RestrictionManager{
 constructor({countries=new CountryManager(),relations=new RelationManager()}={}){this.countries=countries;this.relations=relations;JsonManager.ensureFile(FILE,[])} load(){const d=JsonManager.load(FILE,[]);return Array.isArray(d)?d:[]} save(d){JsonManager.save(FILE,d)}
 list({countryId=null,activeOnly=false}={}){return this.load().filter(x=>(!countryId||x.issuer_country_id===String(countryId)||x.target_country_id===String(countryId))&&(!activeOnly||x.status==='active')).map(clone)}
 impose({issuerCountryId,targetCountryId,actorId,type='embargo',category='all',durationDays=7,reason='decisão diplomática'}){const a=this.countries.get(issuerCountryId),b=this.countries.get(targetCountryId);if(!a||!b)throw new Error('País não encontrado.');if(a.leader_id!==String(actorId))throw new Error('Apenas o líder pode impor restrições.');if(a.id===b.id)throw new Error('Não é possível aplicar restrição ao próprio país.');if(!['embargo','sanction'].includes(type))throw new Error('Tipo inválido.');const now=new Date();const r={id:`restriction_${crypto.randomUUID()}`,type,issuer_country_id:a.id,target_country_id:b.id,category:String(category||'all').slice(0,40),reason:String(reason).slice(0,160),status:'active',created_at:now.toISOString(),expires_at:new Date(now.getTime()+Math.max(1,Math.min(90,Math.trunc(Number(durationDays)||7))*86400000)).toISOString()};const all=this.load();all.push(r);this.save(all);this.relations.adjust(a.id,b.id,type==='embargo'?-20:-12,`${type} aplicado`);return clone(r)}
 revoke(id,actorId){const all=this.load(),i=all.findIndex(x=>x.id===String(id));if(i<0)throw new Error('Restrição não encontrada.');const r=all[i],issuer=this.countries.get(r.issuer_country_id);if(issuer?.leader_id!==String(actorId))throw new Error('Apenas o emissor pode revogar.');r.status='revoked';r.revoked_at=new Date().toISOString();this.save(all);return clone(r)}
 activeBetween(a,b){const now=Date.now();return this.load().filter(r=>r.status==='active'&&Date.parse(r.expires_at)>now&&((r.issuer_country_id===String(a)&&r.target_country_id===String(b))||(r.issuer_country_id===String(b)&&r.target_country_id===String(a))))}
 blocksTrade(a,b,itemCategory='all'){return this.activeBetween(a,b).some(r=>r.type==='embargo'&&(r.category==='all'||r.category===String(itemCategory)))}
}
