import path from 'node:path';import crypto from 'node:crypto';import { JsonManager } from '../core/JsonManager.js';import { DIPLOMACY_DATA_DIR } from '../config/settings.js';import { CountryManager } from '../world/CountryManager.js';import { RelationManager } from './RelationManager.js';
const FILE=path.join(DIPLOMACY_DATA_DIR,'treaties.json');const TYPES=new Set(['non_aggression','trade','mutual_defense','research']);const clone=v=>structuredClone(v);
export class TreatyManager{
 constructor({countries=new CountryManager(),relations=new RelationManager()}={}){this.countries=countries;this.relations=relations;JsonManager.ensureFile(FILE,[])} load(){const d=JsonManager.load(FILE,[]);return Array.isArray(d)?d:[]} save(d){JsonManager.save(FILE,d)}
 get(id){return clone(this.load().find(x=>x.id===String(id))??null)} list({countryId=null,status=null}={}){return this.load().filter(x=>(!countryId||(x.country_ids??[]).includes(String(countryId)))&&(!status||x.status===status)).map(clone)}
 propose({proposerCountryId,targetCountryId,actorId,type='non_aggression',durationDays=30}){const a=this.countries.get(proposerCountryId),b=this.countries.get(targetCountryId);if(!a||!b)throw new Error('País não encontrado.');if(a.leader_id!==String(actorId))throw new Error('Apenas o líder pode propor tratados.');if(a.id===b.id)throw new Error('Tratado exige dois países.');if(!TYPES.has(type))throw new Error('Tipo de tratado inválido.');const now=new Date().toISOString();const t={id:`treaty_${crypto.randomUUID()}`,type,country_ids:[a.id,b.id],proposer_country_id:a.id,target_country_id:b.id,status:'pending',duration_days:Math.max(1,Math.min(365,Math.trunc(Number(durationDays)||30))),created_at:now,accepted_at:null,expires_at:null};const all=this.load();all.push(t);this.save(all);return clone(t)}
 accept(treatyId,countryId,actorId){const all=this.load(),i=all.findIndex(x=>x.id===String(treatyId));if(i<0)throw new Error('Tratado não encontrado.');const t=all[i],c=this.countries.get(countryId);if(!c||c.leader_id!==String(actorId)||t.target_country_id!==c.id)throw new Error('Apenas o líder do país convidado pode aceitar.');if(t.status!=='pending')throw new Error('Tratado não está pendente.');const now=new Date();t.status='active';t.accepted_at=now.toISOString();t.expires_at=new Date(now.getTime()+t.duration_days*86400000).toISOString();this.relations.adjust(t.country_ids[0],t.country_ids[1],t.type==='mutual_defense'?25:15,'tratado firmado');this.save(all);return clone(t)}
 end(treatyId,actorId){const all=this.load(),i=all.findIndex(x=>x.id===String(treatyId));if(i<0)throw new Error('Tratado não encontrado.');const t=all[i];const allowed=t.country_ids.some(id=>this.countries.get(id)?.leader_id===String(actorId));if(!allowed)throw new Error('Apenas líderes signatários podem encerrar o tratado.');t.status='ended';t.ended_at=new Date().toISOString();this.save(all);return clone(t)}
 hasActive(a,b,type=null){const now=Date.now();return this.load().some(t=>t.status==='active'&&(!t.expires_at||Date.parse(t.expires_at)>now)&&t.country_ids.includes(String(a))&&t.country_ids.includes(String(b))&&(!type||t.type===type))}
}
